## YAML Template.
---
#spring:
#    datasource:
#        url: jdbc:mysql://localhost:3306/foodfam?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#        username: root
#        password: aldrin

spring:
    datasource:
        url: jdbc:mysql://root:JMeyXekMDRL1BvBdeeR5@containers-us-west-182.railway.app:6766/railway?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
        password: JMeyXekMDRL1BvBdeeR5
##        driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
##        show-sql: true
#        hibernate:
#            ddl-auto: update
##            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
##        properties:
##            hibernate:
##                dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 783125222252-jvtjco0rn3p56ck6jgs8o9gtu2t0nkb4.apps.googleusercontent.com
              clientSecret: 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
              scope:
                - email
                - profile
            facebook:
              clientId: 151383627671358
              clientSecret: a35dd72a2a16a8c617e5b858cab1b905
#              callbackURL: http://localhost:8080/oauth2/authorization/facebook
              scope:
                - email
                - public_profile   
##          authorization-grant-type: authorization_code
##          redirect-uri-template: localhost:8080/login/oauth2/code/{registrationId}
##          client-name: Facebook

            github:
                clientId: 053e68ff9e9e15a0d464
                clientSecret: c35877af1dbc40f65eddbef0fdba43216f365a23
                scope:
                    - user:email
                    - read:user
            


     
                
                
